import type { Metadata } from "next";
import { Crimson_Pro, Barlow_Condensed } from 'next/font/google';
import "./globals.css";
import { IconProvider } from "@/contexts/icon-provider";
import { Analytics } from "@vercel/analytics/next"

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
});

const barlow = Barlow_Condensed({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <IconProvider value={{ size: 24, weight: 'regular', className: 'icon' }}>
      <html lang="en">
        <body
          className={`${crimsonPro.variable} ${barlow.variable} antialiased`}
        >
          {children}
        </body>
        <Analytics />   
      </html>
   </IconProvider>
  );
}
